[package]
name = "gpui-todos"
version = "0.1.1"
edition = "2024"

[[bin]]
path = "src/main.rs"
name = "todos"

[dependencies]
anyhow = "1"
gpui = "0.2"
rust-embed = "8"
serde = "1"
serde_json = "1"
unicode-segmentation = "1"
