[package]
name = "gpui-todo-list"
version = "0.1.0"
edition = "2021"

[[bin]]
path = "src/main.rs"
name = "todos"

[dependencies]
gpui = "0.2"
unicode-segmentation = "1.11.0"
rust-embed = "8.2.0"
serde = "1.0.195"
serde_json = "1.0.111"
anyhow = "1"
