[package]
name = "gpui-todo-list"
version = "0.1.0"
edition = "2024"

[[bin]]
path = "src/main.rs"
name = "todos"

[dependencies]
anyhow = "1.0.100"
gpui = "0.2.1"
rust-embed = "8.7.2"
serde = "1.0.228"
serde_json = "1.0.145"
unicode-segmentation = "1.12.0"
